---
- name: Set up macOS machine
  hosts: all

  # These variables get loaded first, before pre_tasks is run
  vars_files:
    - default.config.yml

  # Variables get overridden by any in config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps
      tags: ["mas"]

  tasks:
    - import_tasks: tasks/stow.yml
      when: configure_dotfiles
      tags: ["dotfiles"]

    - import_tasks: tasks/macos.yml
      when: configure_osx
      tags: ["osx"]

    - import_tasks: tasks/stow.yml
      when: configure_dotfiles
      tags: ["dotfiles"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - name: Run post-provision task files in a block.
      tags: ["post"]
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
