#!/usr/bin/env bash

dynamic-fzf() {
    local term_height
    if [ -n "$TMUX" ]; then
        term_height=$(tmux display-message -p '#{client_height}')
    else
        term_height=$(tput lines)
    fi

    local min_lines=15
    local height_percent=$((min_lines * 100 / term_height))

    local final_height
    if [ $height_percent -gt 10 ]; then
        final_height="${height_percent}%"
    else
        final_height="10%"
    fi

    local input_data=$(cat)
    local max_width=$(echo "$input_data" | wc -L)
    local term_width
    if [ -n "$TMUX" ]; then
        term_width=$(tmux display-message -p '#{client_width}')
    else
        term_width=$(tput cols)
    fi

    local adjusted_width=$((max_width + 10))
    local max_allowed_width=$((term_width * 80 / 100))
    if [ $adjusted_width -gt $max_allowed_width ]; then
        adjusted_width=$max_allowed_width
    fi

    local width_percent=$((adjusted_width * 100 / term_width))

    echo "$input_data" | fzf-tmux -p -h "$final_height" -w "${width_percent}%" \
        --border rounded \
        --margin 0% \
        --padding 0% \
        --info hidden \
        --no-scrollbar \
        "$@"
}
