#!/usr/bin/env bash

selected=$(find ~/.config ~/Documents/projects -mindepth 1 -maxdepth 1 -type d | dynamic-fzf)

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmuxinator_path="$HOME/.config/tmuxinator"

if [[ -f "$tmuxinator_path/$selected_name.yml" ]]; then
  tmuxinator $selected_name
  exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
  tmux attach -t $selected_name
else
  tmux switch-client -t $selected_name
fi
