---
configure_dotfiles: true
configure_terminal: true
configure_osx: true
# work or personal
machine_type: "personal"

dotfiles_repo: https://github.com/santiagohervella/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/projects/dotfiles
# Just using this ansible role to clone for now and will use GNU stow to link
# TODO: If this is all you use this role for then just create a git task
dotfiles_files: []

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bat
  - csvlens
  - dockutil
  - git
  - gh
  - ffmpeg
  - jq
  - lazygit
  - neovim
  - node
  - nodenv
  - tmux
  - tmuxinator

homebrew_taps: []

homebrew_cask_appdir: /Applications

# List of apps common to all machine types
common_hombrew_cask_apps:
  - alt-tab
  - arc
  - postman
  - zed
  # Terminals, gotta catch 'em all!
  - alacritty
  - ghostty
  - handbrake
  - iterm2
  - kitty
  - wezterm

personal_homebrew_cask_apps:
  - transmission

work_homebrew_cask_apps:
  - docker
  - beekeeper-studio
  - sequel-ace # Beekeeper competitor, let's see if I like it

homebrew_cask_apps: |
  {% if machine_type == 'personal' %}
    {% set apps = common_hombrew_cask_apps + personal_homebrew_cask_apps %}
  {% elif machine_type == 'work' %}
    {% set apps = common_hombrew_cask_apps + work_homebrew_cask_apps %}
  {% else %}
    {% set apps = common_hombrew_cask_apps %}
  {% endif %}
  {{ apps | join(', ') }}

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.macos.sh --no-restart"
osx_personal_script: "~/.macos-personal-only.sh --no-restart"
osx_work_script: "~/.macos-work-only.sh --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
