# Initial inspiration for this config comes from here:
# https://github.com/omerxx/dotfiles/blob/master/starship/starship.toml

add_newline = false
# A minimal left prompt
format = """$directory$git_branch${custom.git_status_simplified}$git_state$character"""
palette = "catppuccin_mocha"
right_format = ''
command_timeout = 1000

[character]
# This seems to occasionally cause issues, commenting out for new
# vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''

# Found what I was wanted for git status here:
# https://github.com/starship/starship/discussions/1252#discussioncomment-692829
[custom.git_status_simplified]
when = 'test -n "$(git status --porcelain)"'
symbol = '●'
style = 'yellow bold'
format = '[$symbol]($style) '
shell = [ 'zsh' ]

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
